
# List of file names
file_names = [
    "Streaming_History_Audio_2015-2018_0.json",
    "Streaming_History_Audio_2018-2021_1.json",
    "Streaming_History_Audio_2021-2022_2.json",
    "Streaming_History_Audio_2022-2024_3.json",
    "Streaming_History_Audio_2024_4.json"
]


# Dictionary to map albums to be merged
album_mapping = {

       "How You Get The Girl ": "1989",
    "Enchanted ": "Speak Now", 
    "I Knew You Were Trouble ": "Red",
    "Fearless": "Fearless",
    "This Is The Sound Of...Love":  "Fearless",
    "Love Story (Taylor’s Version)": "Fearless",
    "Fearless (Taylor's Version)": "Fearless",
    "Mr. Perfectly Fine (Taylor’s Version) (From The Vault)": "Fearless",
    "Fearless (Taylor’s Version): The I Remember What You Said Last Night Chapter": "Fearless",
    "You All Over Me (feat. Maren Morris) (Taylor’s Version) (From The Vault)": "Fearless",
    "Mr. Perfectly Fine (Taylor’s Version) (From The Vault)": "Fearless",
    "You All Over Me (feat. Maren Morris) (Taylor’s Version) (From The Vault)": "Fearless",
    "Message In A Bottle (Fat Max G Remix) (Taylor’s Version)": "Fearless",
    "If This Was A Movie (Taylor's Version)": "Fearless",
    "Love Story (Taylor's Version)": "Fearless",
    "Fearless (Taylor's Version): The I Remember What You Said Last Night Chapter": "Fearless",
    "Mr. Perfectly Fine (Taylor's Version) (From The Vault)": "Fearless",
    "You All Over Me (feat. Maren Morris) (Taylor's Version) (From The Vault)": "Fearless",


    "Look What You Made Me Do": "reputation",
    "Gorgeous": "reputation",
    "...Ready For It?": "reputation",
    "Call It What You Want": "reputation",
    "reputation Stadium Tour Surprise Song Playlist": "reputation",
    "Bad Blood": "reputation",
    "Delicate": "reputation",
    "Gameday Country": "reputation",
    
    "Wildest Dreams (Taylor's Version)": "1989",
    "This Love (Taylor’s Version)": "1989",
    "Restaurante Pop": "1989",
    "This Love (Taylor's Version)": "1989",

    "folklore: the long pond studio sessions (from the Disney+ special) - deluxe edition": "folklore",
    "You Need To Calm Down": "Lover",
    "ME! (feat. Brendon Urie of Panic! At The Disco)": "Lover",
    "ME!": "Lover",
    "Lover (Remix) [feat. Shawn Mendes]": "Lover",
    "The Man": "Lover",
    "Cornelia Street": "Lover",
	"Death By A Thousand Cuts": "Lover",
    "Daylight": "Lover",
    "The Archer": "Lover",
    "All Of The Girls You Loved Before": "Lover",
    "The Cruelest Summer": "Lover",
    "pov: best friends falling in love": "Lover",

    "folklore: the yeah I showed up at your party chapter": "folklore",
    "cardigan": "folklore",
    "folklore: the saltbox house chapter": "folklore",
    "folklore: the long pond studio sessions (from the Disney+ special)": "folklore",
    "the lakes": "folklore",

    "willow": "evermore",
    'the "dropped your hand while dancing" chapter': 'evermore',

    "Beautiful Ghosts": "Other",
    "The Hunger Games: Songs From District 12 And Beyond": "Other",
    "Sweeter Than Fiction": "Other",
    "Carolina": "Other",

    "All Too Well (Sad Girl Autumn Version) - Recorded at Long Pond Studios": "Red",
    "Eyes Open (Taylor's Version)": "Red",
    "Safe & Sound (Taylor's Version)": "Red",
    "The More Red (Taylor’s Version) Chapter": "Red",
    "Message In A Bottle (Fat Max G Remix) (Taylor's Version)": "Red",
    "Ronan": "Red",
    "The More Red (Taylor's Version) Chapter": "Red",

    "Speak Now World Tour Live": "Speak Now",

    "You're Losing Me (From The Vault)": "Midnights",
    "Lavender Haze": "Midnights",

    "Christmas Tree Farm": "Other",
    "Only The Young": "Other",
    "The Taylor Swift Holiday Collection": "Other",
    "Spotify Singles": "Other",
    "Hannah Montana The Movie": "Other", 

    "THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY": "THE TORTURED POETS DEPARTMENT",
    "Fearless - Big Machine Radio Release Special": "Fearless",
    "Fearless - International Version": "Fearless",
    "Fearless - Platinum Edition": "Fearless",
    "I Can Do It With a Broken Heart": "THE TORTURED POETS DEPARTMENT",
    "Fortnight (feat. Post Malone)": "THE TORTURED POETS DEPARTMENT",
    "Anti-Hero": "Midnights",
    "Anti-Hero (feat. Bleachers)": "Midnights",
    "Cats: Highlights From The Motion Picture Soundtrack": "Other",

    "1989 (Taylor's Version)": "1989",
    "Red (Taylor's Version)": "Red",
    "Speak Now (Taylor's Version)": "Speak Now",
    "Fearless (Taylor's Version)": "Fearless",

}


taylor_version_mapping = {

 
    "Back To December - Acoustic": "Back To December",
    "Anti-Hero (feat. Bleachers)": "Anti-Hero",
    "Anti-Hero - Acoustic Version": "Anti-Hero",
    "Back To December - US Version": "Back To December",
    "Tim McGraw": "Tim McGraw",
    "Fifteen": "Fifteen",
    "Fifteen (Taylor's Version)": "Fifteen",
    "Teardrops On My Guitar": "Teardrops On My Guitar",
    "Teardrops On My Guitar - Radio Single Remix": "Teardrops On My Guitar",
    "Teardrops on My Guitar - Pop Version": "Teardrops On My Guitar",
    "Enchanted - Live/2011": "Enchanted",
    "Enchanted (Taylor's Version)": "Enchanted",
    "Only The Young - Featured in Miss Americana": "Only The Young",
    "Mary's Song (Oh My My My)": "Mary's Song (Oh My My My)",
    "Christmases When You Were Mine": "Christmases When You Were Mine",
    "Silent Night": "Silent Night",
    "White Christmas": "White Christmas",
    "Santa Baby": "Santa Baby",
    "Crazier": "Crazier",
    "Cold As You": "Cold As You",
    "A Perfectly Good Heart": "A Perfectly Good Heart",
    "The Outside": "The Outside",
    "The Best Day": "The Best Day",
    "The Best Day (Taylor's Version)": "The Best Day",
    "Sweeter Than Fiction": "Sweeter Than Fiction",
    "Better Man (Taylor's Version) (From The Vault)": "Better Man",
    "Babe (Taylor's Version) (From The Vault)": "Babe",
    "Bye Bye Baby (Taylor's Version) (From The Vault)": "Bye Bye Baby",
    "Forever Winter (Taylor's Version) (From The Vault)": "Forever Winter",
    "That's When (feat. Keith Urban) (Taylor's Version) (From The Vault)": "That's When",
    "We Were Happy (Taylor's Version) (From The Vault)": "We Were Happy",
    "You All Over Me (feat. Maren Morris) (Taylor's Version) (From The Vault)": "You All Over Me",
    "Don't You (Taylor's Version) (From The Vault)": "Don't You",
    "Nothing New (feat. Phoebe Bridgers) (Taylor's Version) (From The Vault)": "Nothing New",
    "Message In A Bottle (Taylor's Version) (From The Vault)": "Message In A Bottle",
    "Timeless (Taylor's Version) (From The Vault)": "Timeless",
    "Electric Touch (feat. Fall Out Boy) (Taylor's Version) (From The Vault)": "Electric Touch",
    "Castles Crumbling (feat. Hayley Williams) (Taylor's Version) (From The Vault)": "Castles Crumbling",
    "When Emma Falls in Love (Taylor's Version) (From The Vault)": "When Emma Falls In Love",
    "Suburban Legends (Taylor's Version) (From The Vault)": "Suburban Legends",
    "Slut! (Taylor's Version) (From The Vault)": "Slut!",
    "Say Don't Go (Taylor's Version) (From The Vault)": "Say Don't Go",
    "Now That We Don't Talk (Taylor's Version) (From The Vault)": "Now That We Don't Talk",
    "Is It Over Now? (Taylor's Version) (From The Vault)": "Is It Over Now?",
    "You're Losing Me (From The Vault)": "You're Losing Me",
    "Hits Different": "Hits Different",
    "Lavender Haze - Jungle Remix": "Lavender Haze",
    "Lavender Haze - Felix Jaehn Remix": "Lavender Haze",
    "Karma": "Karma",
    "Karma (feat. Ice Spice)": "Karma",
    "Snow On The Beach (feat. Lana Del Rey)": "Snow On The Beach",
    "Snow On The Beach (feat. More Lana Del Rey)": "Snow On The Beach",
    "I Forgot That You Existed": "I Forgot That You Existed",
    "The Man": "The Man",
    "The Archer": "The Archer",
    "Afterglow": "Afterglow",
    "Paper Rings": "Paper Rings",
    "Cruel Summer": "Cruel Summer",
    "Cornelia Street": "Cornelia Street",
    "Daylight": "Daylight",
    "Death By A Thousand Cuts": "Death By A Thousand Cuts",
    "Soon You'll Get Better (feat. The Chicks)": "Soon You'll Get Better",
    "You Need To Calm Down": "You Need To Calm Down",
    "Lover": "Lover",
    "London Boy": "London Boy",
    "I Think He Knows": "I Think He Knows",
    "Miss Americana & The Heartbreak Prince": "Miss Americana & The Heartbreak Prince",
    "False God": "False God",
    "It's Nice To Have A Friend": "It's Nice To Have A Friend",
    "Delicate": "Delicate",
    "Call It What You Want": "Call It What You Want",
    "Look What You Made Me Do": "Look What You Made Me Do",
    "New Year's Day": "New Year's Day",
    "Death By A Thousand Cuts": "Death By A Thousand Cuts",
    "Death By A Thousand Cuts - Live From Paris": "Death By A Thousand Cuts",
    "Cornelia Street": "Cornelia Street",
    "Cornelia Street - Live From Paris": "Cornelia Street",
    "Delicate": "Delicate",
    "Delicate - Seeb Remix": "Delicate",
    "Delicate - Sawyr And Ryan Tedder Mix": "Delicate",
    "Delicate - Recorded at The Tracking Room Nashville": "Delicate",
    "Daylight": "Daylight",
    "Daylight - Live From Paris": "Daylight",
    "The Archer": "The Archer",
    "The Archer - Live From Paris": "The Archer",
    "Christmas Tree Farm": "Christmas Tree Farm",
    "Christmas Tree Farm - Recorded Live at the 2019 iHeartRadio Jingle Ball": "Christmas Tree Farm",
    "Forever & Always": "Forever & Always",
    "Forever & Always (Taylor's Version)": "Forever & Always",
    "Forever & Always - Piano Version": "Forever & Always",
    "Forever & Always (Piano Version) (Taylor's Version)": "Forever & Always",
    "All Too Well (Sad Girl Autumn Version) - Recorded at Long Pond Studios": "All Too Well",
    "The Moment I Knew": "The Moment I Knew",
    "The Moment I Knew (Taylor's Version)": "The Moment I Knew",
    "Begin Again": "Begin Again",
    "Begin Again (Taylor's Version)": "Begin Again",
    "Girl At Home": "Girl At Home",
    "Girl At Home (Taylor's Version)": "Girl At Home",
    "New Romantics": "New Romantics",
    "New Romantics (Taylor's Version)": "New Romantics",
    "Hey Stephen": "Hey Stephen",
    "Hey Stephen (Taylor's Version)": "Hey Stephen",
    "Mean": "Mean",
    "Mean (Taylor's Version)": "Mean",
    "Red - Original Demo Recording": "Red",
    "State Of Grace - Acoustic": "State Of Grace",
    "State Of Grace - Acoustic Version": "State Of Grace",
    "State Of Grace (Acoustic Version) (Taylor's Version)": "State Of Grace",
    "I Can See You (Taylor's Version) (From The Vault)": "I Can See You",
    "Love Story - US Album Version": "Love Story",
    "Love Story (Taylor's Version) - Elvira Remix": "Love Story",
    "The Other Side Of The Door": "The Other Side Of The Door",
    "The Other Side Of The Door (Taylor's Version)": "The Other Side Of The Door",
    "Mine - US Version": "Mine",
    "Mine - Live/2011": "Mine",
    "Mine - POP Mix": "Mine",
    "Safe & Sound - from The Hunger Games Soundtrack": "Red",
    "Safe & Sound (feat. Joy Williams and John Paul White) (Taylor's Version)": "Red",
    "Eyes Open": "Eyes Open",
    "Eyes Open (Taylor's Version)": "Eyes Open",
    "Sweeter Than Fiction - From \"One Chance\" Soundtrack": "Sweeter Than Fiction",
    "Today Was A Fairytale": "Today Was A Fairytale",
    "Today Was A Fairytale (Taylor's Version)": "Today Was A Fairytale",
    "Jump Then Fall": "Jump Then Fall",
    "Jump Then Fall (Taylor's Version)": "Jump Then Fall",
    "Ronan": "Ronan",
    "Ronan (Taylor's Version)": "Ronan",
    "Willow": "Willow",
    "Wildest Dreams": "Wildest Dreams",
    "Wildest Dreams (Taylor's Version)": "Wildest Dreams",
    "Breathe": "Breathe",
    "Breathe (feat. Colbie Caillat) (Taylor's Version)": "Breathe",
    "If This Was A Movie": "If This Was A Movie",
    "If This Was A Movie (Taylor's Version)": "If This Was A Movie",
    "Back To December / Apologize / You're Not Sorry - Live 2011": "Back To December",
    "You're Not Sorry": "You're Not Sorry",
    "You're Not Sorry (Taylor's Version)": "You're Not Sorry",
    "Change": "Change",
    "Change (Taylor's Version)": "Change",
    "Untouchable": "Untouchable",
    "Untouchable (Taylor's Version)": "Untouchable",
    "Ours": "Ours",
    "Ours (Taylor's Version)": "Ours",
    "Our Song": "Our Song",
    "All Too Well": "All Too Well",
    "All Too Well (Taylor's Version)": "All Too Well",
    "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)": "All Too Well",
    "Last Kiss": "Last Kiss",
    "Last Kiss (Taylor's Version)": "Last Kiss",
    "Innocent": "Innocent",
    "Innocent (Taylor's Version)": "Innocent",
    "Dear John - Live/2011": "Dear John",
    "Dear John (Taylor's Version)": "Dear John",
    "Welcome To New York": "Welcome To New York",
    "Welcome To New York (Taylor's Version)": "Welcome To New York",
    "The Story Of Us - Live 2011": "The Story Of Us",
    "The Story Of Us - US Version": "The Story Of Us",
    "The Story Of Us (Taylor's Version)": "The Story Of Us",
    "How You Get The Girl": "How You Get The Girl",
    "How You Get The Girl (Taylor's Version)": "How You Get The Girl",
    "Everything Has Changed": "Everything Has Changed",
    "Everything Has Changed (feat. Ed Sheeran) (Taylor's Version)": "Everything Has Changed",
    "White Horse": "White Horse",
    "White Horse (Taylor's Version)": "White Horse",
    "Starlight": "Starlight",
    "Starlight (Taylor's Version)": "Starlight",
    "Blank Space": "Blank Space",
    "Blank Space (Taylor's Version)": "Blank Space",
    "Out Of The Woods": "Out Of The Woods",
    "Out Of The Woods (Taylor's Version)": "Out Of The Woods",
    "All You Had To Do Was Stay": "All You Had To Do Was Stay",
    "All You Had To Do Was Stay (Taylor's Version)": "All You Had To Do Was Stay",
    "Shake It Off": "Shake It Off",
    "Shake It Off (Taylor's Version)": "Shake It Off",
    "I Wish You Would": "I Wish You Would",
    "I Wish You Would (Taylor's Version)": "I Wish You Would",
    "I Knew You Were Trouble": "I Knew You Were Trouble",
    "I Knew You Were Trouble (Taylor's Version)": "I Knew You Were Trouble",
    "I Knew You Were Trouble.": "I Knew You Were Trouble",
    "State Of Grace": "State Of Grace",
    "State Of Grace (Taylor's Version)": "State Of Grace",
    "Red": "Red",
    "Red (Taylor's Version)": "Red",
    "Treacherous": "Treacherous",
    "Treacherous (Taylor's Version)": "Treacherous",
    "22": "22",
    "22 (Taylor's Version)": "22",
    "All Too Well": "All Too Well",
    "All Too Well (Taylor's Version)": "All Too Well",
    "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)": "All Too Well",
    "Love Story": "Love Story",
    "Love Story (Taylor's Version)": "Love Story",
    "Wildest Dreams": "Wildest Dreams",
    "Wildest Dreams (Taylor's Version)": "Wildest Dreams",
    "Enchanted": "Enchanted",
    "Enchanted (Taylor's Version)": "Enchanted",
    "Fearless": "Fearless",
    "Fearless (Taylor's Version)": "Fearless",
    "Back To December": "Back To December",
    "Back To December (Taylor's Version)": "Back To December",
    "Mine": "Mine",
    "Mine (Taylor's Version)": "Mine",
    "Speak Now": "Speak Now",
    "Speak Now (Taylor's Version)": "Speak Now",
    "Dear John": "Dear John",
    "Dear John (Taylor's Version)": "Dear John",
    "You Belong With Me": "You Belong With Me",
    "You Belong With Me (Taylor's Version)": "You Belong With Me",
    "This Love": "This Love",
    "This Love (Taylor's Version)": "This Love",
    "Cruel Summer": "Cruel Summer",
    "Cruel Summer - Live from TS | The Eras Tour": "Cruel Summer",
    "cardigan": "cardigan",
    "cardigan - cabin in candlelight version": "cardigan",
    "cardigan - the long pond studio sessions": "cardigan",
    "the 1": "the 1",
    "the 1 - the long pond studio sessions": "the 1",
    "august": "august",
    "august - the long pond studio sessions": "august",
    "betty": "betty",
    "betty - Live from the 2020 Academy of Country Music Awards": "betty",
    "betty - the long pond studio sessions": "betty",
    "You Need To Calm Down": "You Need To Calm Down",
    "You Need To Calm Down - Live From Paris": "You Need To Calm Down",
    "You Need To Calm Down - Clean Bandit Remix": "You Need To Calm Down",
    "Lavender Haze": "Lavender Haze",
    "Lavender Haze - Acoustic Version": "Lavender Haze",
    "Lavender Haze - Felix Jaehn Remix": "Lavender Haze",
    "willow": "willow",
    "willow - moonlit witch version": "willow",
    "willow - lonely witch version": "willow",
    "willow - dancing witch version (Elvira remix)": "willow",

    "Haunted - Live/2011": "Haunted",
    "Better Than Revenge - Live/2011": "Better Than Revenge",
    "I Want You Back - Live/2011": "I Want You Back",
    "Mean - Live/2011": "Mean",
    "Speak Now - Live/2011": "Speak Now",
    "Dear John - Live 2011": "Dear John",

    "Drops Of Jupiter - Live 2011": "Drops Of Jupiter",
    "Fortnight (feat. Post Malone) - BLOND:ISH Remix": "Fortnight (feat. Post Malone)",
    "I Can Do It With a Broken Heart - Instrumental": "I Can Do It With a Broken Heart",


    "Hey Stephen - Commentary": "Hey Stephen",

    "I Know Places - Voice Memo": "I Know Places",
    "I Wish You Would - Voice Memo": "I Wish You Would",

    "Blank Space - Voice Memo": "Blank Space",
    "You Are In Love (Taylor's Version)": "You Are In Love",
    "Never Grow Up (Taylor's Version)": "Never Grow Up",

    "the lakes - original version": "the lakes",

    "September - Recorded at The Tracking Room Nashville": "September",

    "Bad Blood (feat. Kendrick Lamar) (Taylor's Version)": "Bad Blood",
    "Carolina - From The Motion Picture “Where The Crawdads Sing”": "Carolina",

    "Wonderland (Taylor's Version)": "Wonderland", 
    "I Know Places (Taylor's Version)": "I Know Places",

    "Foolish One (Taylor's Version) (From The Vault)": "Foolish One",
    "Treacherous - Original Demo Recording": "Treacherous",
    "Better Than Revenge (Taylor's Version)": "Better Than Revenge",
    "Long Live (Taylor's Version)": "Long Live",
    "Sparks Fly - Live/2011": "Sparks Fly",
    "Lover (Remix) [feat. Shawn Mendes]": "Lover",
    "The Way I Loved You (Taylor's Version)": "The Way I Loved You",

    "epiphany - the long pond studio sessions": "epiphany",
    "invisible string - the long pond studio sessions": "invisible string",
    "illicit affairs - the long pond studio sessions": "illicit affairs",
    "this is me trying - the long pond studio sessions": "this is me trying",

    "Style (Taylor's Version)": "Style",
    "the lakes - the long pond studio sessions": "the lakes",
    "mad woman - the long pond studio sessions": "mad woman",
    "mirrorball - the long pond studio sessions": "mirrorball",
    "seven - the long pond studio sessions": "seven",
    "The Lucky One (Taylor's Version)": "The Lucky One",
    "Sad Beautiful Tragic (Taylor's Version)": "Sad Beautiful Tragic",
    "it's time to go - bonus track": "it's time to go",
    "my tears ricochet - the long pond studio sessions": "my tears ricochet",
    "Come Back...Be Here (Taylor's Version)": "Come Back...Be Here",
    "right where you left me - bonus track": "right where you left me",
    "Holy Ground (Taylor's Version)": "Holy Ground",

    "The Last Time (feat. Gary Lightbody of Snow Patrol) (Taylor's Version)": "The Last Time",
    "the last great american dynasty - the long pond studio sessions": "the last great american dynasty",
    "Run (feat. Ed Sheeran) (Taylor's Version) (From The Vault)": "Run",
    "I Almost Do (Taylor's Version)": "I Almost Do",
    "\"Slut!\" (Taylor's Version) (From The Vault)": "Slut!",
    "exile (feat. Bon Iver) - the long pond studio sessions": "exile",
    "Mr. Perfectly Fine (Taylor's Version) (From The Vault)": "Mr. Perfectly Fine",
    "The Very First Night (Taylor's Version) (From The Vault)": "The Very First Night",
    "I Bet You Think About Me (feat. Chris Stapleton) (Taylor's Version) (From The Vault)": "I Bet You Think About Me",
    "We Are Never Ever Getting Back Together (Taylor's Version)": "We Are Never Ever Getting Back Together",

    "Message In A Bottle (Fat Max G Remix) (Taylor's Version)": "Message In A Bottle",
    "Sparks Fly (Taylor's Version)": "Sparks Fly",
    "Superstar (Taylor's Version)": "Superstar",
    "Ours - Live/2011": "Ours",
    "Beautiful Ghosts - From The Motion Picture Soundtrack \"Cats\"": "Beautiful Ghosts",
    "...Ready For It? - BloodPop® Remix": "...Ready For It?",
    "Tell Me Why (Taylor's Version)": "Tell Me Why",
    "Carolina - \"Where The Crawdads Sing\" - Video Edition": "Carolina",
    "Come In With The Rain (Taylor's Version)": "Come In With The Rain",
    "Lover - First Dance Remix": "Lover",
    "ME! - Live From Paris": "ME!",
    "Haunted (Taylor's Version)": "Haunted",
    "Superman (Taylor's Version)": "Superman",
    "Stay Stay Stay (Taylor's Version)": "Stay Stay Stay",
    "peace - the long pond studio sessions": "peace",
    "hoax - the long pond studio sessions": "hoax",
    "Bad Blood (Taylor's Version)": "Bad Blood",
    "Haunted - Acoustic Version": "Haunted",
    "Clean (Taylor's Version)": "Clean",
    "the lakes - bonus track": "the lakes",

}


# At the end of your script, modify the last two lines to:

# Define album colors (this should be at the top with other constants, but we'll put it here for the fix)
album_colors = {
    "folklore": "#D3D3D3",
    "Red": "#FF0000",
    "THE TORTURED POETS DEPARTMENT": "#333333",
    "Midnights": "#00008B",
    "1989": "#87CEEB",
    "Lover": "#FFC0CB",
    "evermore": "#800000",
    "reputation": "#000000",
    "Speak Now": "#800080",
    "Fearless": "#FFFF00",
    "Taylor Swift": "#008000",
    "Other": "#FFFFFF",
    "The Life of a Showgirl": "#FF8E1B",
}
