name: Daily Update
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:      # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Run update script
        run: python insummation.py  # Your script name
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push